// utils/seedData.js — complete roadmaps + real quiz questions

import storage from '../lib/storage';

const roadmaps = [
  {
    id: 'tcs-fullstack',
    title: 'TCS Full Stack Developer',
    description: 'Complete preparation for TCS NQT Full Stack Developer roles. Master React, Node.js, MongoDB, REST APIs, and AWS deployment strategies used in TCS projects.',
    category: 'development',
    difficulty: 'Intermediate',
    duration: '12–16 weeks',
    prerequisites: ['Basic JavaScript', 'HTML & CSS fundamentals', 'Basic programming concepts', 'Familiarity with command line'],
    skills: ['React.js', 'Node.js', 'MongoDB', 'Express.js', 'AWS', 'REST APIs', 'Git', 'Docker basics'],
    steps: [
      {
        title: 'Frontend Fundamentals',
        description: 'Master HTML5, CSS3, and modern JavaScript (ES6+). Build the foundation that every TCS full-stack role expects.',
        topics: ['Semantic HTML5', 'CSS Grid & Flexbox', 'JavaScript ES6+ (let/const, arrow functions, destructuring)', 'Async/Await & Promises', 'DOM Manipulation & Events', 'Fetch API & JSON'],
        resources: ['MDN Web Docs', 'JavaScript.info', 'CSS Tricks — Complete Guide to Flexbox', 'freeCodeCamp Responsive Web Design'],
        duration: '2–3 weeks',
        projects: ['Personal portfolio website', 'Interactive product landing page with vanilla JS'],
      },
      {
        title: 'React.js — Core to Advanced',
        description: 'Deep dive into React ecosystem. TCS projects heavily use React; understanding hooks, state management, and routing is mandatory.',
        topics: ['JSX & Component architecture', 'useState, useEffect, useContext', 'React Router v6', 'Custom hooks', 'Performance — memo, useMemo, useCallback', 'React Query basics'],
        resources: ['Official React documentation (react.dev)', 'Scrimba React course', 'React Patterns by Michael Chan'],
        duration: '3–4 weeks',
        projects: ['E-commerce product listing with cart', 'GitHub user search app using Fetch API'],
      },
      {
        title: 'Backend with Node.js & Express',
        description: 'Build production-grade REST APIs with Node.js. Learn authentication, middleware, and error handling patterns used in enterprise TCS codebases.',
        topics: ['Node.js event loop & modules', 'Express.js routing & middleware', 'RESTful API design', 'JWT authentication', 'Input validation', 'Error handling middleware'],
        resources: ['Express.js official docs', 'Node.js Best Practices (GitHub goldbergyoni)', 'JWT.io introduction'],
        duration: '3 weeks',
        projects: ['Blog API with CRUD + JWT auth', 'File upload API with multer'],
      },
      {
        title: 'MongoDB & Database Design',
        description: 'NoSQL data modeling with MongoDB — schema design, Mongoose ODM, aggregation pipelines, and indexing strategies.',
        topics: ['MongoDB CRUD operations', 'Mongoose schemas & models', 'Relationships — embedding vs referencing', 'Aggregation pipeline', 'Indexing & query optimization', 'Atlas free tier setup'],
        resources: ['MongoDB University M001 (free)', 'Mongoose official documentation', 'MongoDB Schema Design Patterns'],
        duration: '2 weeks',
        projects: ['User management system with MongoDB', 'Analytics dashboard backend'],
      },
      {
        title: 'Cloud Deployment — AWS',
        description: 'Deploy full-stack applications to AWS. Understand EC2, S3, and basic DevOps practices that TCS expects from mid-level developers.',
        topics: ['AWS EC2 — launch & configure', 'S3 for static hosting & file storage', 'Environment variables & secrets', 'NGINX reverse proxy basics', 'CI/CD with GitHub Actions', 'Basic Docker containerization'],
        resources: ['AWS Free Tier (aws.amazon.com)', 'DigitalOcean tutorials (proxy patterns)', 'Docker getting started guide'],
        duration: '2–3 weeks',
        projects: ['Deploy full-stack app to EC2', 'Static site on S3 + CloudFront'],
      },
      {
        title: 'System Design & TCS Interview Prep',
        description: 'Prepare for TCS technical rounds with system design concepts, coding practice, and TCS-specific interview patterns.',
        topics: ['System design fundamentals — scalability, load balancing', 'Database design patterns', 'TCS NQT coding section — arrays, strings, recursion', 'LLD — designing classes and modules', 'Git workflows used in teams', 'Code review best practices'],
        resources: ['System Design Primer (GitHub)', 'LeetCode Easy-Medium practice', 'TCS NQT previous year papers', 'Grokking the System Design Interview'],
        duration: '2 weeks',
        projects: ['System design case study write-up', 'Solve 50 LeetCode problems'],
      },
    ],
  },
  {
    id: 'infosys-data-science',
    title: 'Infosys Data Science Analyst',
    description: 'Structured path to Infosys Data Science and Analytics roles. Cover Python, pandas, machine learning, SQL, and data visualization tools used in Infosys Nia platform.',
    category: 'data-ai',
    difficulty: 'Intermediate',
    duration: '10–14 weeks',
    prerequisites: ['Basic Python or any programming language', 'High school mathematics', 'Basic statistics concepts'],
    skills: ['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'SQL', 'Tableau / Power BI', 'Matplotlib', 'Seaborn'],
    steps: [
      {
        title: 'Python for Data Science',
        description: 'Python is the language of data science at Infosys. Master the fundamentals through a data lens.',
        topics: ['Python syntax, lists, dicts, sets', 'Functions, lambda, list comprehensions', 'File I/O & JSON handling', 'OOP fundamentals', 'Virtual environments & pip', 'Jupyter notebooks'],
        resources: ['Python.org official tutorial', 'Kaggle Python course (free)', 'Real Python articles'],
        duration: '2–3 weeks',
        projects: ['Data cleaning script for messy CSV', 'Automated report generator'],
      },
      {
        title: 'Data Manipulation — Pandas & NumPy',
        description: 'The workhorse of data science. Infosys analysts use pandas daily for ETL, cleaning, and feature engineering.',
        topics: ['DataFrame & Series operations', 'Indexing — loc, iloc, boolean masking', 'GroupBy & pivot tables', 'Handling missing values', 'Merging & reshaping data', 'NumPy arrays & vectorized operations'],
        resources: ['Pandas official documentation', '10 Minutes to pandas', 'Kaggle Pandas micro-course'],
        duration: '2–3 weeks',
        projects: ['EDA on a Kaggle dataset', 'Sales data aggregation pipeline'],
      },
      {
        title: 'Machine Learning with Scikit-learn',
        description: 'Build and evaluate ML models. Infosys Nia uses AutoML but expects analysts to understand model fundamentals.',
        topics: ['Supervised: Linear, Logistic Regression, Decision Trees', 'Ensemble: Random Forest, Gradient Boosting', 'Unsupervised: K-Means clustering, PCA', 'Model evaluation — cross-validation, confusion matrix, ROC-AUC', 'Feature engineering & selection', 'Hyperparameter tuning with GridSearchCV'],
        resources: ['Scikit-learn user guide', 'Kaggle Intro to ML course', 'StatQuest YouTube (Josh Starmer)'],
        duration: '3 weeks',
        projects: ['Customer churn prediction model', 'Customer segmentation with K-Means'],
      },
      {
        title: 'SQL for Data Analysis',
        description: 'SQL is tested in every Infosys data role interview. Master it to the level expected in analytics teams.',
        topics: ['SELECT, WHERE, GROUP BY, HAVING, ORDER BY', 'JOINs — INNER, LEFT, RIGHT, FULL', 'Subqueries & CTEs', 'Window functions — ROW_NUMBER, RANK, LEAD, LAG', 'Aggregation functions', 'Query optimization basics'],
        resources: ['Mode SQL Tutorial', 'SQLZoo (interactive)', 'LeetCode SQL problems'],
        duration: '2 weeks',
        projects: ['50 SQL practice queries', 'Sales analytics SQL report'],
      },
      {
        title: 'Data Visualization & Storytelling',
        description: 'Communicate insights effectively. Infosys clients expect clean dashboards and clear data narratives.',
        topics: ['Matplotlib & Seaborn charts', 'Plotly interactive visualizations', 'Power BI fundamentals', 'Dashboard design principles', 'Statistical storytelling', 'Presenting to non-technical stakeholders'],
        resources: ['Seaborn gallery & tutorials', 'Power BI learning (Microsoft)', 'Cole Knaflic — Storytelling with Data'],
        duration: '1–2 weeks',
        projects: ['COVID-19 data visualization notebook', 'Power BI sales dashboard'],
      },
    ],
  },
  {
    id: 'wipro-cloud',
    title: 'Wipro Cloud & DevOps Engineer',
    description: 'Comprehensive roadmap for Wipro Cloud infrastructure and DevOps roles. Master AWS/Azure, Docker, Kubernetes, CI/CD pipelines, and Infrastructure as Code used in Wipro cloud practices.',
    category: 'cloud-devops',
    difficulty: 'Advanced',
    duration: '8–12 weeks',
    prerequisites: ['Linux command line basics', 'Basic networking concepts', 'At least one programming language'],
    skills: ['AWS / Azure', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions', 'Linux', 'Python scripting', 'Jenkins'],
    steps: [
      {
        title: 'Linux & Networking Foundations',
        description: 'Cloud and DevOps work happens on Linux. Master the command line, permissions, networking, and scripting.',
        topics: ['File system navigation & permissions', 'Process management — ps, top, kill', 'Networking — SSH, curl, netstat, DNS', 'Shell scripting — bash basics', 'Cron jobs & scheduling', 'Package management — apt, yum'],
        resources: ['Linux Journey (linuxjourney.com)', 'The Linux Command Line (William Shotts — free online)', 'OverTheWire Bandit wargames'],
        duration: '1–2 weeks',
        projects: ['Server setup & hardening script', 'Log analysis bash script'],
      },
      {
        title: 'Docker & Containerization',
        description: 'Containers are the foundation of modern cloud deployments. Wipro projects run everything in containers.',
        topics: ['Docker architecture & concepts', 'Dockerfile best practices', 'docker-compose for multi-service apps', 'Container networking & volumes', 'Image optimization & multi-stage builds', 'Docker registry — push & pull'],
        resources: ['Docker official getting started', 'Play with Docker (labs.play-with-docker.com)', 'Docker deep dive (Nigel Poulton)'],
        duration: '2 weeks',
        projects: ['Containerize a Node.js app', 'Multi-container app with docker-compose'],
      },
      {
        title: 'AWS Core Services',
        description: 'AWS is Wipro\'s primary cloud partner. These services appear in 90% of Wipro cloud projects.',
        topics: ['IAM — users, roles, policies', 'EC2 & Auto Scaling', 'S3 — storage classes & lifecycle', 'VPC — subnets, security groups, NAT', 'RDS & DynamoDB basics', 'CloudWatch monitoring'],
        resources: ['AWS Free Tier', 'AWS Cloud Practitioner Essentials (free)', 'Adrian Cantrill AWS courses'],
        duration: '2–3 weeks',
        projects: ['3-tier architecture on AWS', 'Serverless API with Lambda + API Gateway'],
      },
      {
        title: 'CI/CD & DevOps Practices',
        description: 'Automate the entire software delivery pipeline. Wipro clients demand zero-downtime deployments.',
        topics: ['Git branching strategies — GitFlow, trunk-based', 'GitHub Actions workflows', 'Jenkins pipelines', 'Automated testing in CI', 'Blue-green & canary deployments', 'Artifact registries — ECR, ACR'],
        resources: ['GitHub Actions official docs', 'Jenkins user handbook', 'DevOps Handbook (condensed summaries)'],
        duration: '2 weeks',
        projects: ['Full CI/CD pipeline for a Node.js app', 'Automated Docker build & push on merge'],
      },
      {
        title: 'Kubernetes & IaC',
        description: 'Kubernetes orchestration and Terraform IaC are tested in Wipro L2+ roles. Essential for senior growth.',
        topics: ['Kubernetes architecture — pods, services, deployments', 'kubectl commands', 'ConfigMaps & Secrets', 'HorizontalPodAutoscaler', 'Terraform — providers, resources, state', 'Terraform modules & workspaces'],
        resources: ['Kubernetes official docs', 'Terraform getting started', 'KodeKloud free Kubernetes labs'],
        duration: '2–3 weeks',
        projects: ['Deploy app to local Kubernetes (minikube)', 'Terraform AWS VPC module'],
      },
    ],
  },
  {
    id: 'hcl-machine-learning',
    title: 'HCL Machine Learning Engineer',
    description: 'End-to-end ML engineering path for HCL Technologies roles. From model training to production deployment with MLflow, FastAPI, and monitoring.',
    category: 'data-ai',
    difficulty: 'Advanced',
    duration: '14–18 weeks',
    prerequisites: ['Python proficiency', 'Linear algebra basics', 'Probability & statistics', 'Some exposure to ML concepts'],
    skills: ['Python', 'TensorFlow / PyTorch', 'Scikit-learn', 'MLflow', 'FastAPI', 'Docker', 'SQL', 'Feature engineering'],
    steps: [
      {
        title: 'Machine Learning Foundations',
        description: 'Solidify theoretical and practical ML foundations before moving to deep learning.',
        topics: ['Supervised, unsupervised, reinforcement learning taxonomy', 'Bias-variance tradeoff', 'Regularization — L1, L2, Elastic Net', 'Ensemble methods — Bagging, Boosting, Stacking', 'Feature selection techniques', 'Evaluation metrics — precision, recall, F1, RMSE, R²'],
        resources: ['Hands-On ML with Scikit-Learn & TensorFlow (Aurélien Géron)', 'StatQuest with Josh Starmer (YouTube)', 'Kaggle Learn — ML'],
        duration: '3 weeks',
        projects: ['End-to-end Kaggle competition notebook', 'Feature importance study on tabular dataset'],
      },
      {
        title: 'Deep Learning — Neural Networks',
        description: 'Neural networks power HCL\'s AI practice. Understand architectures from MLPs to transformers.',
        topics: ['Perceptrons to multilayer networks', 'Backpropagation & gradient descent', 'CNNs for image recognition', 'RNNs, LSTMs for sequence data', 'Transformers & attention mechanism', 'Transfer learning & fine-tuning'],
        resources: ['fast.ai Practical Deep Learning (free)', 'Deep Learning Specialization (Coursera — audit free)', '3Blue1Brown Neural Networks series'],
        duration: '4 weeks',
        projects: ['Image classifier with CNN (CIFAR-10)', 'Sentiment analysis with fine-tuned BERT'],
      },
      {
        title: 'MLOps & Model Deployment',
        description: 'Getting models to production is where HCL ML engineers spend most of their time. Master the full MLOps cycle.',
        topics: ['MLflow experiment tracking & model registry', 'Feature stores concepts', 'FastAPI for model serving', 'Docker containerization of ML models', 'Model monitoring — data drift, concept drift', 'A/B testing for models'],
        resources: ['MLflow official docs', 'FastAPI tutorial', 'Made with ML (madewithml.com)'],
        duration: '3 weeks',
        projects: ['Train → track → deploy pipeline with MLflow + FastAPI', 'Drift monitoring dashboard'],
      },
      {
        title: 'Data Engineering for ML',
        description: 'ML engineers at HCL manage data pipelines. Understanding ETL and data quality is mandatory.',
        topics: ['Apache Spark fundamentals', 'Data validation with Great Expectations', 'SQL for feature engineering', 'Apache Kafka basics', 'Data versioning with DVC', 'ETL pipeline design'],
        resources: ['Spark SQL getting started', 'DVC (dvc.org) documentation', 'Data Engineering Zoomcamp (free)'],
        duration: '2 weeks',
        projects: ['PySpark data transformation pipeline', 'DVC-tracked model with versioned datasets'],
      },
    ],
  },
  {
    id: 'cognizant-testing',
    title: 'Cognizant QA & Test Engineer',
    description: 'Complete QA engineering roadmap for Cognizant roles. Manual testing fundamentals, Selenium automation, API testing with Postman/RestAssured, and CI-integrated test pipelines.',
    category: 'testing',
    difficulty: 'Beginner',
    duration: '6–8 weeks',
    prerequisites: ['Basic programming knowledge (any language)', 'Understanding of software development lifecycle'],
    skills: ['Selenium WebDriver', 'Java / Python', 'Postman', 'RestAssured', 'JIRA', 'TestNG / JUnit', 'CI/CD integration', 'SQL for test data'],
    steps: [
      {
        title: 'Manual Testing Foundations',
        description: 'Every Cognizant QA engineer starts with manual testing principles. Understand the SDLC from a quality perspective.',
        topics: ['SDLC vs STLC', 'Test case design techniques — equivalence partitioning, boundary value analysis', 'Defect lifecycle & severity vs priority', 'Test plan & test strategy', 'JIRA for bug tracking', 'Agile testing — sprint, regression, smoke'],
        resources: ['ISTQB Foundation syllabus (free PDF)', 'Guru99 Manual Testing course', 'Software Testing Help tutorials'],
        duration: '1–2 weeks',
        projects: ['Write 50 test cases for an e-commerce app', 'Log 10 bugs in JIRA with proper templates'],
      },
      {
        title: 'Selenium WebDriver Automation',
        description: 'Selenium with Java is the standard at Cognizant automation teams. Master locators, waits, and Page Object Model.',
        topics: ['Selenium setup with Maven + TestNG', 'XPath & CSS selectors', 'Implicit, explicit, fluent waits', 'Page Object Model (POM)', 'Data-driven testing with Excel/CSV', 'Screenshot on failure & reporting'],
        resources: ['Selenium official documentation', 'ToolsQA Selenium tutorials', 'Udemy Selenium with Java (look for free coupons)'],
        duration: '3 weeks',
        projects: ['Automate login & checkout flow for a demo site', 'Data-driven test suite with POM'],
      },
      {
        title: 'API Testing — Postman & RestAssured',
        description: 'API testing is a core skill tested in Cognizant interviews. Learn both manual (Postman) and code-based (RestAssured) approaches.',
        topics: ['REST API concepts — methods, status codes, headers', 'Postman — collections, environments, scripts', 'RestAssured — GET/POST/PUT/DELETE validation', 'JSON schema validation', 'Authentication — Bearer, OAuth in tests', 'Newman CLI for CI integration'],
        resources: ['Postman Learning Center', 'RestAssured official docs', 'API testing with Postman (YouTube FreeCodeCamp)'],
        duration: '1–2 weeks',
        projects: ['Postman collection with 20+ API tests', 'RestAssured test suite for a public API'],
      },
      {
        title: 'CI/CD for QA & Test Pipelines',
        description: 'Cognizant teams run test suites in pipelines. Integrate your test suite with Jenkins or GitHub Actions.',
        topics: ['Jenkins — create a job, run Maven tests', 'GitHub Actions for test automation', 'Allure reports setup', 'Parallel test execution', 'Test coverage metrics', 'Shift-left testing principles'],
        resources: ['Jenkins Pipeline documentation', 'GitHub Actions for Java', 'Allure Framework docs'],
        duration: '1 week',
        projects: ['CI pipeline that runs Selenium tests on each commit', 'Allure report published to GitHub Pages'],
      },
    ],
  },
  {
    id: 'accenture-consulting',
    title: 'Accenture Technology Consultant',
    description: 'Holistic preparation for Accenture Technology Analyst and Consulting roles. Business analysis, SAP/Salesforce basics, data analytics, presentation skills, and Accenture interview process.',
    category: 'consulting',
    difficulty: 'Beginner',
    duration: '8–10 weeks',
    prerequisites: ['Good communication skills', 'Basic Excel', 'Analytical mindset'],
    skills: ['Business Analysis', 'Data Analytics', 'PowerPoint / Slides', 'SQL', 'Salesforce basics', 'Agile/Scrum', 'Case study solving', 'Excel'],
    steps: [
      {
        title: 'Business Analysis & Requirements',
        description: 'Accenture consultants bridge business and technology. Understand requirements gathering, process mapping, and stakeholder communication.',
        topics: ['Business requirements vs. functional requirements', 'Use cases & user stories', 'Process flow diagrams — BPMN', 'Stakeholder mapping', 'Gap analysis', 'BRD & FRS document writing'],
        resources: ['BABOK Guide v3 (summarized versions on YouTube)', 'Lucidchart for process diagrams', 'Business Analysis Body of Knowledge — free articles'],
        duration: '2 weeks',
        projects: ['BRD for a fictional app', 'Process flow diagram for an e-commerce checkout'],
      },
      {
        title: 'Data Analytics & Excel',
        description: 'Data-driven consulting is Accenture\'s core value. Excel and SQL analytics are tested in every intake.',
        topics: ['Advanced Excel — VLOOKUP, INDEX/MATCH, pivot tables', 'Excel charts and dashboards', 'SQL — SELECT, JOIN, aggregation, subqueries', 'Data cleaning best practices', 'Basic statistics for business', 'Google Sheets equivalent skills'],
        resources: ['Excel skills for business (Coursera — audit free)', 'Mode SQL Tutorial', 'ExcelJet.net formulas reference'],
        duration: '2–3 weeks',
        projects: ['Sales analytics Excel dashboard', 'Customer retention SQL analysis'],
      },
      {
        title: 'Agile, Scrum & Project Delivery',
        description: 'Accenture runs projects in Agile. Understanding Scrum ceremonies, sprint planning, and velocity tracking is expected from Day 1.',
        topics: ['Agile manifesto & 12 principles', 'Scrum roles — PO, Scrum Master, Dev Team', 'Sprint planning, standups, retrospectives', 'JIRA for Agile project management', 'Kanban vs. Scrum', 'Velocity, burndown charts'],
        resources: ['Scrum Guide (scrumguides.org — free)', 'Atlassian Agile Coach articles', 'JIRA tutorial on Atlassian University'],
        duration: '1–2 weeks',
        projects: ['Plan a 2-week sprint for a sample project', 'JIRA board setup and sprint simulation'],
      },
      {
        title: 'Accenture Interview Preparation',
        description: 'Accenture has a specific process — cognitive assessment, tech MCQs, communication test, case interview. Prepare for each stage.',
        topics: ['Accenture Cognitive Assessment patterns', 'Technical MCQ topics — OOP, DBMS, networking', 'Case study frameworks — MECE, SWOT, Porter\'s 5 Forces', 'Communication & group discussion tips', 'Technical presentation skills', 'Common Accenture HR questions'],
        resources: ['Accenture careers site (official process description)', 'Prep Insta for Accenture aptitude', 'Case in Point (Marc Cosentino — free summaries)'],
        duration: '2 weeks',
        projects: ['Solve 3 full case studies', 'Record a 5-minute mock presentation'],
      },
    ],
  },
];

const quizzes = [
  {
    id: 'tcs-fullstack',
    title: 'TCS Full Stack Developer Certification',
    duration: 30,
    questions: [
      { q: "What does the React useEffect hook with an empty dependency array [] do?", options: ["Runs on every render", "Runs only once after the first render", "Runs only when state changes", "Never runs"], answer: "Runs only once after the first render" },
      { q: "Which HTTP status code indicates a successfully created resource?", options: ["200 OK", "201 Created", "204 No Content", "301 Moved Permanently"], answer: "201 Created" },
      { q: "What is CORS and why is it needed?", options: ["A caching mechanism for APIs", "A security policy that controls cross-origin requests", "A data compression standard", "A database query language"], answer: "A security policy that controls cross-origin requests" },
      { q: "In MongoDB, which operator is used to find documents where a field value is greater than a given value?", options: ["$gt", "$gte", "$greater", "$more"], answer: "$gt" },
      { q: "What does JWT stand for and what is its primary use?", options: ["JavaScript Web Token — for DOM manipulation", "JSON Web Token — for stateless authentication", "Java Web Token — for Java APIs", "JSON Write Token — for database writes"], answer: "JSON Web Token — for stateless authentication" },
      { q: "In CSS Flexbox, which property aligns items along the cross axis?", options: ["justify-content", "align-items", "flex-direction", "flex-wrap"], answer: "align-items" },
      { q: "What is the purpose of the Node.js event loop?", options: ["To manage memory allocation", "To handle asynchronous callbacks without blocking the main thread", "To parse JavaScript syntax", "To compile TypeScript"], answer: "To handle asynchronous callbacks without blocking the main thread" },
      { q: "Which React hook is used for sharing state across components without prop drilling?", options: ["useState", "useEffect", "useContext", "useRef"], answer: "useContext" },
      { q: "What does 'REST' stand for in REST API?", options: ["Relational Entity State Transfer", "Representational State Transfer", "Remote Execution State Transfer", "Rapid Endpoint State Transfer"], answer: "Representational State Transfer" },
      { q: "In Express.js, what does middleware do?", options: ["It renders HTML templates", "It compresses JavaScript files", "It intercepts and processes requests between receiving and responding", "It connects to the database"], answer: "It intercepts and processes requests between receiving and responding" },
      { q: "What is the difference between == and === in JavaScript?", options: ["There is no difference", "=== checks value and type, == only checks value with type coercion", "== checks value and type, === only checks value", "=== is used for objects only"], answer: "=== checks value and type, == only checks value with type coercion" },
      { q: "Which AWS service is used for scalable object storage?", options: ["EC2", "RDS", "S3", "Lambda"], answer: "S3" },
      { q: "What is the MongoDB aggregation pipeline stage that filters documents?", options: ["$group", "$project", "$match", "$sort"], answer: "$match" },
      { q: "In React, what triggers a component re-render?", options: ["Only when props change", "Only when state changes", "When state or props change, or when context updates", "Only when the page is refreshed"], answer: "When state or props change, or when context updates" },
      { q: "What is the purpose of .gitignore?", options: ["To list branches to delete", "To specify files Git should not track", "To define merge conflict resolution rules", "To list remote repositories"], answer: "To specify files Git should not track" },
      { q: "Which HTTP method is idempotent and used to completely replace a resource?", options: ["POST", "PATCH", "PUT", "DELETE"], answer: "PUT" },
      { q: "What is the 'N+1 query problem' in databases?", options: ["Running the same query N+1 times unnecessarily due to lazy loading", "Having N+1 columns in a table", "A query that returns N+1 more rows than expected", "A database with N+1 tables"], answer: "Running the same query N+1 times unnecessarily due to lazy loading" },
      { q: "In JavaScript, what does the spread operator (...) do?", options: ["Creates a new function", "Multiplies array elements", "Expands an iterable into individual elements", "Loops over an array"], answer: "Expands an iterable into individual elements" },
      { q: "What is the purpose of package.json in a Node.js project?", options: ["To store environment variables", "To define project metadata, scripts, and dependencies", "To configure the web server", "To store API keys"], answer: "To define project metadata, scripts, and dependencies" },
      { q: "Which CSS property creates a grid layout?", options: ["display: flex", "display: grid", "display: table", "display: block"], answer: "display: grid" },
      { q: "What is React's Virtual DOM?", options: ["A real DOM stored in memory", "A JavaScript representation of the DOM used to optimize updates", "A browser extension for React", "A server-side rendering technique"], answer: "A JavaScript representation of the DOM used to optimize updates" },
      { q: "What does async/await in JavaScript handle?", options: ["Synchronous code only", "Asynchronous operations, making them appear synchronous", "Class inheritance", "DOM events"], answer: "Asynchronous operations, making them appear synchronous" },
      { q: "In MongoDB, what is an index used for?", options: ["To encrypt data at rest", "To speed up query performance by allowing faster data lookup", "To validate document schema", "To create relationships between collections"], answer: "To speed up query performance by allowing faster data lookup" },
      { q: "Which Node.js module handles HTTP server creation natively?", options: ["fs", "path", "http", "net"], answer: "http" },
      { q: "What is the purpose of environment variables in a web application?", options: ["To style the user interface", "To store configuration and secrets separate from code", "To define database schemas", "To manage user sessions"], answer: "To store configuration and secrets separate from code" },
      { q: "In CSS, what is specificity?", options: ["The speed at which CSS loads", "The rule that determines which CSS declaration applies when multiple rules target the same element", "The number of CSS files in a project", "The order in which stylesheets are loaded"], answer: "The rule that determines which CSS declaration applies when multiple rules target the same element" },
      { q: "What does Docker containerization primarily solve?", options: ["Database scaling", "'It works on my machine' — environment consistency across development, staging, production", "Network latency", "Code compilation speed"], answer: "'It works on my machine' — environment consistency across development, staging, production" },
      { q: "What is a closure in JavaScript?", options: ["A function that terminates early", "A function that retains access to its outer scope even after the outer function has returned", "A class method that is private", "A callback function"], answer: "A function that retains access to its outer scope even after the outer function has returned" },
      { q: "Which React hook is used to access and interact with a DOM element directly?", options: ["useState", "useEffect", "useRef", "useCallback"], answer: "useRef" },
      { q: "In REST API design, which endpoint pattern is most RESTful for getting a specific user?", options: ["GET /getUser?id=5", "POST /user/get/5", "GET /users/5", "GET /fetchUser/5"], answer: "GET /users/5" },
    ],
  },
  {
    id: 'infosys-data-science',
    title: 'Infosys Data Science Analyst Certification',
    duration: 30,
    questions: [
      { q: "What is the difference between supervised and unsupervised learning?", options: ["Supervised uses labeled data; unsupervised finds patterns in unlabeled data", "Supervised is faster than unsupervised", "Unsupervised uses labeled data; supervised does not", "They are the same thing"], answer: "Supervised uses labeled data; unsupervised finds patterns in unlabeled data" },
      { q: "Which pandas method is used to handle missing values by filling them?", options: ["df.fillna()", "df.dropna()", "df.replace()", "df.isnull()"], answer: "df.fillna()" },
      { q: "What does the R-squared (R²) metric measure in regression?", options: ["Model accuracy in classification", "The proportion of variance in the dependent variable explained by the model", "The mean error of predictions", "The number of features used"], answer: "The proportion of variance in the dependent variable explained by the model" },
      { q: "In a confusion matrix, what is a False Positive?", options: ["Model predicted negative, actual was negative", "Model predicted positive, actual was positive", "Model predicted positive, actual was negative", "Model predicted negative, actual was positive"], answer: "Model predicted positive, actual was negative" },
      { q: "What SQL clause is used to filter results after GROUP BY?", options: ["WHERE", "HAVING", "FILTER", "CONDITION"], answer: "HAVING" },
      { q: "What is overfitting in machine learning?", options: ["When a model performs poorly on training data", "When a model learns training data too well and fails to generalize to new data", "When a model has too few parameters", "When training takes too long"], answer: "When a model learns training data too well and fails to generalize to new data" },
      { q: "Which technique is used to reduce dimensionality in datasets?", options: ["K-Means", "PCA (Principal Component Analysis)", "Linear Regression", "Random Forest"], answer: "PCA (Principal Component Analysis)" },
      { q: "What is the purpose of train-test split in machine learning?", options: ["To speed up training", "To evaluate model performance on unseen data and detect overfitting", "To increase dataset size", "To normalize features"], answer: "To evaluate model performance on unseen data and detect overfitting" },
      { q: "In pandas, what does groupby() followed by agg() do?", options: ["Filters rows based on a condition", "Groups rows by a column and applies aggregation functions to each group", "Merges two DataFrames", "Sorts the DataFrame"], answer: "Groups rows by a column and applies aggregation functions to each group" },
      { q: "What is a window function in SQL?", options: ["A function that opens new windows in the browser", "A function that performs a calculation across a set of rows related to the current row without collapsing them", "A function that creates database views", "A function that manages database connections"], answer: "A function that performs a calculation across a set of rows related to the current row without collapsing them" },
      { q: "What does K-Means clustering do?", options: ["Classifies data with labeled examples", "Partitions data into K groups based on feature similarity", "Reduces the number of features", "Predicts continuous values"], answer: "Partitions data into K groups based on feature similarity" },
      { q: "Which cross-validation method is most reliable for small datasets?", options: ["Holdout validation", "K-Fold cross-validation", "Random sampling", "Bootstrap"], answer: "K-Fold cross-validation" },
      { q: "What is feature engineering?", options: ["Building new hardware features", "The process of creating, transforming, or selecting features to improve model performance", "Writing algorithms from scratch", "Deploying ML models to production"], answer: "The process of creating, transforming, or selecting features to improve model performance" },
      { q: "In NumPy, what does broadcasting allow?", options: ["Sending data over a network", "Performing arithmetic operations on arrays of different shapes without explicit looping", "Streaming data in real-time", "Displaying arrays graphically"], answer: "Performing arithmetic operations on arrays of different shapes without explicit looping" },
      { q: "What is the difference between precision and recall?", options: ["They are the same metric", "Precision = TP/(TP+FP); Recall = TP/(TP+FN)", "Precision = TP/(TP+FN); Recall = TP/(TP+FP)", "Precision measures speed; Recall measures accuracy"], answer: "Precision = TP/(TP+FP); Recall = TP/(TP+FN)" },
      { q: "What is L2 regularization (Ridge) primarily used for?", options: ["Increasing model complexity", "Penalizing large weights to prevent overfitting", "Speeding up gradient descent", "Selecting features by zeroing some weights"], answer: "Penalizing large weights to prevent overfitting" },
      { q: "Which SQL JOIN returns all rows from both tables, with NULLs where there is no match?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], answer: "FULL OUTER JOIN" },
      { q: "What is the purpose of the ROC-AUC score?", options: ["To measure regression accuracy", "To measure the ability of a classifier to distinguish between classes across all thresholds", "To count the number of correct predictions", "To measure model training speed"], answer: "To measure the ability of a classifier to distinguish between classes across all thresholds" },
      { q: "In a Random Forest, how are individual trees created?", options: ["Each tree trains on the full dataset", "Each tree trains on a random bootstrap sample of data with random feature subsets", "Trees share weights between each other", "Each tree is trained sequentially on residuals"], answer: "Each tree trains on a random bootstrap sample of data with random feature subsets" },
      { q: "What does 'data normalization' mean in machine learning preprocessing?", options: ["Removing duplicate records", "Scaling features to a similar range (e.g., 0–1) so no feature dominates due to scale", "Converting text to numbers", "Splitting data into train and test"], answer: "Scaling features to a similar range (e.g., 0–1) so no feature dominates due to scale" },
      { q: "Which type of SQL statement modifies data structure (not data)?", options: ["DML — Data Manipulation Language", "DDL — Data Definition Language", "DCL — Data Control Language", "TCL — Transaction Control Language"], answer: "DDL — Data Definition Language" },
      { q: "What is the gradient descent algorithm used for?", options: ["Finding the maximum of a loss function", "Iteratively minimizing a loss function by updating parameters in the direction of the negative gradient", "Calculating derivatives symbolically", "Clustering data points"], answer: "Iteratively minimizing a loss function by updating parameters in the direction of the negative gradient" },
      { q: "What does Seaborn's heatmap typically visualize?", options: ["Geographic data on maps", "Correlation matrices and 2D data distributions", "Time series data", "3D scatter plots"], answer: "Correlation matrices and 2D data distributions" },
      { q: "What is class imbalance and why is it a problem?", options: ["When training data is too large", "When one class significantly outnumbers others, causing models to be biased toward the majority class", "When features are not scaled", "When test data is unavailable"], answer: "When one class significantly outnumbers others, causing models to be biased toward the majority class" },
      { q: "What is the purpose of a Common Table Expression (CTE) in SQL?", options: ["To create permanent database views", "To define a temporary named result set that can be referenced within a SELECT, INSERT, UPDATE, or DELETE", "To store procedures for later execution", "To create database indexes"], answer: "To define a temporary named result set that can be referenced within a SELECT, INSERT, UPDATE, or DELETE" },
      { q: "Which algorithm is typically used for customer churn prediction?", options: ["K-Means clustering", "Logistic Regression or Gradient Boosted Trees", "Linear Regression", "PCA"], answer: "Logistic Regression or Gradient Boosted Trees" },
      { q: "What does pandas df.merge() do?", options: ["Sorts the DataFrame", "Combines two DataFrames based on a common column or index", "Removes duplicate rows", "Reshapes data from wide to long format"], answer: "Combines two DataFrames based on a common column or index" },
      { q: "What is a decision tree's main weakness?", options: ["It cannot handle categorical data", "It tends to overfit on training data, especially deep trees without pruning", "It is too slow to train", "It cannot be used for classification"], answer: "It tends to overfit on training data, especially deep trees without pruning" },
      { q: "What is the purpose of one-hot encoding?", options: ["To compress image data", "To convert categorical variables into a binary matrix so ML algorithms can process them", "To normalize numerical features", "To reduce dataset dimensions"], answer: "To convert categorical variables into a binary matrix so ML algorithms can process them" },
      { q: "Which metric is most appropriate for evaluating a model on a highly imbalanced dataset?", options: ["Accuracy", "F1-Score or AUC-ROC", "Mean Squared Error", "R-Squared"], answer: "F1-Score or AUC-ROC" },
    ],
  },
  {
    id: 'wipro-cloud',
    title: 'Wipro Cloud & DevOps Engineer Certification',
    duration: 30,
    questions: [
      { q: "What is the primary purpose of Docker containerization?", options: ["To replace virtual machines entirely", "To package applications with their dependencies for consistent environment-independent deployment", "To increase CPU performance", "To manage databases"], answer: "To package applications with their dependencies for consistent environment-independent deployment" },
      { q: "What does IAM stand for in AWS?", options: ["Internet Access Management", "Identity and Access Management", "Internal Application Monitoring", "Infrastructure Asset Management"], answer: "Identity and Access Management" },
      { q: "Which Linux command shows currently running processes?", options: ["ls", "ps aux", "cd", "grep"], answer: "ps aux" },
      { q: "What is a Kubernetes Pod?", options: ["A cluster of nodes", "The smallest deployable unit in Kubernetes, containing one or more containers", "A network policy", "A persistent storage volume"], answer: "The smallest deployable unit in Kubernetes, containing one or more containers" },
      { q: "What is Infrastructure as Code (IaC)?", options: ["Writing code that runs on physical hardware", "Managing and provisioning infrastructure through machine-readable configuration files rather than manual processes", "Programming language for cloud providers", "A monitoring framework"], answer: "Managing and provisioning infrastructure through machine-readable configuration files rather than manual processes" },
      { q: "What is the difference between a Docker image and a Docker container?", options: ["They are the same thing", "An image is a static template; a container is a running instance of an image", "A container is a static template; an image is a running instance", "Images are for Windows, containers are for Linux"], answer: "An image is a static template; a container is a running instance of an image" },
      { q: "Which AWS service provides serverless compute?", options: ["EC2", "ECS", "Lambda", "RDS"], answer: "Lambda" },
      { q: "What does CI/CD stand for?", options: ["Code Integration / Code Deployment", "Continuous Integration / Continuous Delivery (or Deployment)", "Cloud Infrastructure / Cloud Delivery", "Centralized Integration / Centralized Deployment"], answer: "Continuous Integration / Continuous Delivery (or Deployment)" },
      { q: "What is the purpose of Terraform's state file?", options: ["To store application logs", "To track the current state of deployed infrastructure so Terraform can determine what changes to apply", "To cache Terraform provider plugins", "To encrypt sensitive variables"], answer: "To track the current state of deployed infrastructure so Terraform can determine what changes to apply" },
      { q: "In Linux, which command changes file permissions?", options: ["chown", "chmod", "chgrp", "mv"], answer: "chmod" },
      { q: "What is a VPC in AWS?", options: ["A virtual private cloud — an isolated virtual network in AWS", "A virtual processor cluster", "A content delivery network", "A database replication service"], answer: "A virtual private cloud — an isolated virtual network in AWS" },
      { q: "What does a load balancer do?", options: ["Stores application data", "Distributes incoming traffic across multiple servers to ensure availability and reliability", "Monitors server CPU usage", "Encrypts network traffic"], answer: "Distributes incoming traffic across multiple servers to ensure availability and reliability" },
      { q: "What is the purpose of Kubernetes ConfigMaps?", options: ["To store encrypted secrets", "To provide non-sensitive configuration data to pods without hardcoding it in images", "To configure the Kubernetes API server", "To define network policies"], answer: "To provide non-sensitive configuration data to pods without hardcoding it in images" },
      { q: "Which Git command creates a new branch and switches to it?", options: ["git branch new-branch", "git checkout -b new-branch", "git merge new-branch", "git clone new-branch"], answer: "git checkout -b new-branch" },
      { q: "What is a blue-green deployment?", options: ["Deploying to Linux and Windows simultaneously", "Running two identical environments (blue=active, green=new) and switching traffic after validation", "A Docker networking mode", "A Kubernetes scaling strategy"], answer: "Running two identical environments (blue=active, green=new) and switching traffic after validation" },
      { q: "What does the AWS S3 storage class 'Glacier' offer?", options: ["High-performance SSD storage", "Very low-cost archival storage with retrieval times of minutes to hours", "In-memory caching", "Real-time data streaming"], answer: "Very low-cost archival storage with retrieval times of minutes to hours" },
      { q: "What is the purpose of SSH?", options: ["To send emails securely", "To establish a secure encrypted remote shell connection to a server", "To synchronize files between servers", "To monitor server metrics"], answer: "To establish a secure encrypted remote shell connection to a server" },
      { q: "What is a Docker multi-stage build used for?", options: ["Running multiple services in one container", "Creating smaller final images by using temporary build stages that don't persist in the final image", "Building images for multiple architectures", "Running builds in parallel"], answer: "Creating smaller final images by using temporary build stages that don't persist in the final image" },
      { q: "What is Kubernetes HorizontalPodAutoscaler used for?", options: ["Scaling cluster nodes vertically", "Automatically scaling the number of pod replicas based on CPU or custom metrics", "Distributing pods across availability zones", "Managing pod storage volumes"], answer: "Automatically scaling the number of pod replicas based on CPU or custom metrics" },
      { q: "What is the purpose of NGINX in a deployment setup?", options: ["A container orchestration tool", "A web server and reverse proxy that routes traffic to backend services", "A database management system", "A cloud monitoring service"], answer: "A web server and reverse proxy that routes traffic to backend services" },
      { q: "What does 'idempotent' mean in the context of infrastructure?", options: ["Operations that always produce different results", "Operations that produce the same result regardless of how many times they are applied", "Operations that require human approval", "Operations that cannot be reversed"], answer: "Operations that produce the same result regardless of how many times they are applied" },
      { q: "Which AWS service is used to monitor cloud resources and applications?", options: ["CloudTrail", "CloudWatch", "CloudFormation", "CloudFront"], answer: "CloudWatch" },
      { q: "What is the difference between TCP and UDP?", options: ["TCP is faster; UDP is more reliable", "TCP is connection-oriented and reliable; UDP is connectionless and faster but less reliable", "TCP is for web traffic; UDP is for email", "There is no difference"], answer: "TCP is connection-oriented and reliable; UDP is connectionless and faster but less reliable" },
      { q: "What is a Kubernetes Deployment resource used for?", options: ["Deploying the Kubernetes cluster itself", "Declaring the desired state of pods and managing rolling updates and rollbacks", "Exposing pods to external traffic", "Storing persistent data"], answer: "Declaring the desired state of pods and managing rolling updates and rollbacks" },
      { q: "What is 'shift-left' in DevOps?", options: ["Moving the team office location", "Incorporating testing, security, and quality checks earlier in the development process", "Migrating workloads from cloud to on-premise", "Using left-aligned code formatting"], answer: "Incorporating testing, security, and quality checks earlier in the development process" },
      { q: "Which Terraform command applies infrastructure changes?", options: ["terraform plan", "terraform apply", "terraform init", "terraform validate"], answer: "terraform apply" },
      { q: "What is a security group in AWS?", options: ["A group of IAM users", "A virtual firewall that controls inbound and outbound traffic for AWS resources", "A VPN connection", "An S3 bucket policy"], answer: "A virtual firewall that controls inbound and outbound traffic for AWS resources" },
      { q: "What does docker-compose up do?", options: ["Pushes images to Docker Hub", "Builds, creates, starts, and attaches to containers for a service as defined in docker-compose.yml", "Updates Docker to the latest version", "Removes stopped containers"], answer: "Builds, creates, starts, and attaches to containers for a service as defined in docker-compose.yml" },
      { q: "What is the CAP theorem in distributed systems?", options: ["A Kubernetes scheduling algorithm", "The principle that a distributed system can guarantee at most two of: Consistency, Availability, and Partition tolerance simultaneously", "A container networking standard", "A cloud pricing model"], answer: "The principle that a distributed system can guarantee at most two of: Consistency, Availability, and Partition tolerance simultaneously" },
      { q: "What is canary deployment?", options: ["Deploying to production servers only", "Gradually rolling out changes to a small subset of users before full rollout to detect issues early", "Deploying multiple versions simultaneously for A/B testing", "A rollback strategy"], answer: "Gradually rolling out changes to a small subset of users before full rollout to detect issues early" },
    ],
  },
  {
    id: 'hcl-machine-learning',
    title: 'HCL Machine Learning Engineer Certification',
    duration: 30,
    questions: [
      { q: "What is backpropagation in neural networks?", options: ["A forward pass through the network", "The algorithm that calculates gradients by propagating error backwards to update weights", "A data preprocessing step", "A regularization technique"], answer: "The algorithm that calculates gradients by propagating error backwards to update weights" },
      { q: "What is the vanishing gradient problem?", options: ["When gradients become very large and destabilize training", "When gradients become extremely small during backpropagation, causing early layers to learn very slowly", "When the model forgets training data", "When batch size is too small"], answer: "When gradients become extremely small during backpropagation, causing early layers to learn very slowly" },
      { q: "What does a Convolutional Neural Network (CNN) primarily use to detect local patterns?", options: ["Fully connected layers", "Recurrent connections", "Convolutional filters/kernels that slide over the input", "Pooling operations only"], answer: "Convolutional filters/kernels that slide over the input" },
      { q: "What is transfer learning?", options: ["Moving model files between servers", "Using a pre-trained model on a new but related task, rather than training from scratch", "Transferring data between databases", "Converting models between frameworks"], answer: "Using a pre-trained model on a new but related task, rather than training from scratch" },
      { q: "What is MLflow primarily used for?", options: ["Deploying Kubernetes clusters", "Tracking ML experiments, packaging models, and managing the ML lifecycle", "Building neural network architectures", "Data labeling and annotation"], answer: "Tracking ML experiments, packaging models, and managing the ML lifecycle" },
      { q: "What is the attention mechanism in transformers?", options: ["A way to focus the model's computation on hardware accelerators", "A mechanism that allows the model to weigh the importance of different parts of the input sequence when producing each output", "A regularization technique", "A data augmentation strategy"], answer: "A mechanism that allows the model to weigh the importance of different parts of the input sequence when producing each output" },
      { q: "What is data drift in the context of ML models in production?", options: ["Errors in data collection", "A shift in the statistical properties of the input data over time, causing model performance to degrade", "Data being transferred to a new server", "Data compression artifacts"], answer: "A shift in the statistical properties of the input data over time, causing model performance to degrade" },
      { q: "What is the purpose of dropout regularization?", options: ["To drop rows from the training dataset", "To randomly deactivate neurons during training, preventing co-adaptation and reducing overfitting", "To reduce model size for deployment", "To speed up inference"], answer: "To randomly deactivate neurons during training, preventing co-adaptation and reducing overfitting" },
      { q: "What is a hyperparameter?", options: ["A parameter learned during model training", "A configuration setting set before training that controls the learning process (e.g., learning rate, number of layers)", "A metric used to evaluate model performance", "A feature in the training dataset"], answer: "A configuration setting set before training that controls the learning process (e.g., learning rate, number of layers)" },
      { q: "What is the difference between batch gradient descent and stochastic gradient descent (SGD)?", options: ["Batch uses all training data per update; SGD uses one sample per update", "SGD uses all training data per update; Batch uses one sample", "They are identical", "Batch is faster than SGD always"], answer: "Batch uses all training data per update; SGD uses one sample per update" },
      { q: "What is the purpose of a validation set in ML training?", options: ["To provide final model evaluation", "To tune hyperparameters and monitor for overfitting during training without contaminating the test set", "To augment training data", "To normalize input features"], answer: "To tune hyperparameters and monitor for overfitting during training without contaminating the test set" },
      { q: "What is an embedding in deep learning?", options: ["A technique to embed images into documents", "A dense, lower-dimensional representation of high-dimensional or categorical data", "A type of neural network layer", "A data compression algorithm"], answer: "A dense, lower-dimensional representation of high-dimensional or categorical data" },
      { q: "What is Apache Spark used for in ML pipelines?", options: ["Training deep learning models", "Distributed processing of large datasets across a cluster", "Deploying models as REST APIs", "Monitoring model performance"], answer: "Distributed processing of large datasets across a cluster" },
      { q: "What is BERT in NLP?", options: ["A basic English response template", "Bidirectional Encoder Representations from Transformers — a pre-trained language model", "A binary encoding for text", "A recurrent neural network variant"], answer: "Bidirectional Encoder Representations from Transformers — a pre-trained language model" },
      { q: "What is the purpose of batch normalization?", options: ["To split data into batches", "To normalize the inputs of each layer, stabilizing and accelerating training", "To create mini-batches for training", "To normalize output predictions"], answer: "To normalize the inputs of each layer, stabilizing and accelerating training" },
      { q: "What is the F1 score?", options: ["The arithmetic mean of precision and recall", "The harmonic mean of precision and recall", "The geometric mean of accuracy and AUC", "The ratio of true positives to total samples"], answer: "The harmonic mean of precision and recall" },
      { q: "What does DVC (Data Version Control) solve?", options: ["Managing ML model inference speed", "Versioning large data files and ML models alongside code using Git-like workflows", "Deploying models to Kubernetes", "Monitoring data pipelines"], answer: "Versioning large data files and ML models alongside code using Git-like workflows" },
      { q: "What is the purpose of max pooling in CNNs?", options: ["To increase the spatial dimensions of feature maps", "To downsample feature maps by taking the maximum value in each pooling window, reducing computation and providing translation invariance", "To apply non-linear activation functions", "To normalize feature map values"], answer: "To downsample feature maps by taking the maximum value in each pooling window, reducing computation and providing translation invariance" },
      { q: "What is SMOTE used for?", options: ["Reducing dataset size", "Synthetic Minority Over-sampling Technique — generating synthetic samples to handle class imbalance", "Normalizing features", "Selecting important features"], answer: "Synthetic Minority Over-sampling Technique — generating synthetic samples to handle class imbalance" },
      { q: "What is the key idea behind ensemble methods like Gradient Boosting?", options: ["Training one very large model", "Combining multiple weak learners sequentially, each correcting the errors of the previous", "Averaging several identical models", "Using different datasets for each model"], answer: "Combining multiple weak learners sequentially, each correcting the errors of the previous" },
      { q: "What is concept drift in production ML?", options: ["A change in the input data distribution", "A change in the statistical relationship between input features and the target variable over time", "A change in model architecture", "A bug introduced by model updates"], answer: "A change in the statistical relationship between input features and the target variable over time" },
      { q: "Which activation function is most commonly used in the hidden layers of deep neural networks today?", options: ["Sigmoid", "Tanh", "ReLU (Rectified Linear Unit)", "Softmax"], answer: "ReLU (Rectified Linear Unit)" },
      { q: "What is cross-entropy loss used for?", options: ["Regression problems", "Classification problems — it measures the difference between predicted probability distributions and actual labels", "Clustering evaluation", "Feature selection"], answer: "Classification problems — it measures the difference between predicted probability distributions and actual labels" },
      { q: "What is feature importance in tree-based models?", options: ["The order features are processed", "A measure of how much each feature contributes to reducing impurity across all trees in the model", "The number of unique values per feature", "The correlation between features"], answer: "A measure of how much each feature contributes to reducing impurity across all trees in the model" },
      { q: "What is the difference between a model's accuracy and its AUC?", options: ["They measure the same thing differently", "Accuracy measures correct predictions at one threshold; AUC measures performance across all classification thresholds", "AUC only applies to regression", "Accuracy is always higher than AUC"], answer: "Accuracy measures correct predictions at one threshold; AUC measures performance across all classification thresholds" },
      { q: "What is the role of a feature store in MLOps?", options: ["To store ML model weights", "A centralized repository to store, document, and serve features for both training and real-time inference, ensuring consistency", "To archive old datasets", "To log model predictions"], answer: "A centralized repository to store, document, and serve features for both training and real-time inference, ensuring consistency" },
      { q: "What is early stopping in neural network training?", options: ["Stopping training at the first epoch", "Halting training when validation loss stops improving to prevent overfitting", "Stopping when training accuracy reaches 100%", "A learning rate scheduling technique"], answer: "Halting training when validation loss stops improving to prevent overfitting" },
      { q: "What is the main advantage of using FastAPI for ML model serving?", options: ["It is written in Java", "It is a high-performance Python framework with automatic OpenAPI documentation and async support, ideal for ML inference endpoints", "It has built-in model training capabilities", "It requires no coding"], answer: "It is a high-performance Python framework with automatic OpenAPI documentation and async support, ideal for ML inference endpoints" },
      { q: "What is the purpose of learning rate warmup in training large models?", options: ["To increase the learning rate throughout training", "To start with a small learning rate and gradually increase it, preventing unstable updates at the beginning of training", "To reduce the learning rate to zero", "To automatically select the best learning rate"], answer: "To start with a small learning rate and gradually increase it, preventing unstable updates at the beginning of training" },
      { q: "What is the difference between L1 (Lasso) and L2 (Ridge) regularization?", options: ["They are identical", "L1 adds absolute weight penalty and can zero out features (feature selection); L2 adds squared weight penalty and shrinks all weights", "L2 is for classification; L1 is for regression", "L1 is more common in deep learning"], answer: "L1 adds absolute weight penalty and can zero out features (feature selection); L2 adds squared weight penalty and shrinks all weights" },
    ],
  },
  {
    id: 'cognizant-testing',
    title: 'Cognizant QA & Test Engineer Certification',
    duration: 30,
    questions: [
      { q: "What is the difference between verification and validation in software testing?", options: ["They are the same process", "Verification: are we building the product right? Validation: are we building the right product?", "Verification is for functional testing; Validation is for performance testing", "Verification happens after release; Validation before"], answer: "Verification: are we building the product right? Validation: are we building the right product?" },
      { q: "What is boundary value analysis?", options: ["Testing only the middle values of input ranges", "A technique that focuses testing on values at the edges of valid and invalid input ranges", "Testing database boundaries", "Analyzing code boundaries for security"], answer: "A technique that focuses testing on values at the edges of valid and invalid input ranges" },
      { q: "What does the Selenium WebDriver's explicit wait do?", options: ["Waits a fixed time unconditionally", "Waits for a specific condition to be met before proceeding, with a defined timeout", "Pauses all browser activity", "Waits for the page title to change"], answer: "Waits for a specific condition to be met before proceeding, with a defined timeout" },
      { q: "What is the Page Object Model (POM) in Selenium?", options: ["A plugin for Selenium IDE", "A design pattern that creates a class for each web page, separating test logic from UI locators and actions", "A way to record browser actions", "A Selenium grid configuration"], answer: "A design pattern that creates a class for each web page, separating test logic from UI locators and actions" },
      { q: "What is the difference between smoke testing and regression testing?", options: ["They are the same", "Smoke testing verifies basic functionality after a build; regression testing ensures existing functionality isn't broken by changes", "Regression testing is done before smoke testing", "Smoke testing is only for performance"], answer: "Smoke testing verifies basic functionality after a build; regression testing ensures existing functionality isn't broken by changes" },
      { q: "In API testing with Postman, what are environment variables used for?", options: ["To store JavaScript functions", "To store and share values like base URLs and tokens across requests without hardcoding them", "To define test collections", "To run tests in parallel"], answer: "To store and share values like base URLs and tokens across requests without hardcoding them" },
      { q: "What HTTP status code indicates an unauthorized request (missing or invalid authentication)?", options: ["400 Bad Request", "401 Unauthorized", "403 Forbidden", "404 Not Found"], answer: "401 Unauthorized" },
      { q: "What is the difference between a test case and a test scenario?", options: ["They are the same", "Test scenario is a high-level what-to-test; test case is a detailed step-by-step document with expected results", "Test case is higher-level than test scenario", "Test scenarios are only for automation"], answer: "Test scenario is a high-level what-to-test; test case is a detailed step-by-step document with expected results" },
      { q: "What is the XPath expression to find an element containing specific text?", options: ["//tag[@text='value']", "//tag[contains(text(),'value')]", "//tag[text='value']", "//tag[@contains='value']"], answer: "//tag[contains(text(),'value')]" },
      { q: "What is equivalence partitioning?", options: ["Dividing servers into partitions", "Dividing input data into partitions where all values in a partition are expected to behave the same way", "Partitioning test cases by priority", "Splitting test execution across machines"], answer: "Dividing input data into partitions where all values in a partition are expected to behave the same way" },
      { q: "In JIRA, what is the difference between a bug's 'severity' and 'priority'?", options: ["They mean the same thing", "Severity is the impact on functionality; Priority is how urgently it should be fixed from a business perspective", "Priority is technical impact; Severity is business impact", "Severity is set by developers; Priority by testers"], answer: "Severity is the impact on functionality; Priority is how urgently it should be fixed from a business perspective" },
      { q: "What is data-driven testing?", options: ["Testing database performance", "Running the same test with multiple sets of input data from an external source (Excel, CSV, database)", "Writing test scripts in SQL", "Testing only data validation fields"], answer: "Running the same test with multiple sets of input data from an external source (Excel, CSV, database)" },
      { q: "What is the purpose of TestNG annotations like @BeforeMethod and @AfterMethod?", options: ["To write assertions", "To define setup and teardown code that runs before/after each test method", "To skip certain tests", "To configure Selenium WebDriver"], answer: "To define setup and teardown code that runs before/after each test method" },
      { q: "What is a CSS selector in Selenium?", options: ["A way to apply CSS styles", "A locator strategy that finds elements using CSS rules like tag, class, ID, and attribute selectors", "A performance testing metric", "A browser developer tool"], answer: "A locator strategy that finds elements using CSS rules like tag, class, ID, and attribute selectors" },
      { q: "What does 'shift-left testing' mean?", options: ["Moving test environments to the left side of the data center", "Involving testing and quality activities earlier in the development cycle rather than only at the end", "Prioritizing left-to-right language testing", "Running tests from left to right in a pipeline"], answer: "Involving testing and quality activities earlier in the development cycle rather than only at the end" },
      { q: "What is RestAssured used for?", options: ["REST breaks for QA teams", "A Java library for testing REST APIs programmatically with a fluent DSL", "A Postman alternative for manual testing", "A load testing tool"], answer: "A Java library for testing REST APIs programmatically with a fluent DSL" },
      { q: "What is the purpose of Newman in the Postman ecosystem?", options: ["A new Postman UI theme", "A CLI tool that runs Postman collections in CI/CD pipelines without the Postman GUI", "An API documentation generator", "A Postman plugin manager"], answer: "A CLI tool that runs Postman collections in CI/CD pipelines without the Postman GUI" },
      { q: "What is a test plan?", options: ["A plan to plan tests", "A formal document describing the scope, approach, resources, schedule, and objectives of testing for a project", "A list of automated scripts", "A Jira board configuration"], answer: "A formal document describing the scope, approach, resources, schedule, and objectives of testing for a project" },
      { q: "What is the STLC (Software Testing Life Cycle)?", options: ["A Selenium testing framework", "A series of specific activities conducted during the testing process in a planned and systematic way", "A testing hardware standard", "An automated testing pipeline"], answer: "A series of specific activities conducted during the testing process in a planned and systematic way" },
      { q: "What is the difference between black-box and white-box testing?", options: ["Black-box: testers have full code access; White-box: testers have no code access", "Black-box: tests functionality without knowledge of internal code; White-box: tests with knowledge of internal code structure", "They are the same with different color themes", "Black-box is automated; White-box is manual"], answer: "Black-box: tests functionality without knowledge of internal code; White-box: tests with knowledge of internal code structure" },
      { q: "What is an implicit wait in Selenium?", options: ["A wait that never times out", "A global wait that tells WebDriver to wait a specified time before throwing NoSuchElementException on any element lookup", "A wait only for JavaScript execution", "A wait set for specific elements"], answer: "A global wait that tells WebDriver to wait a specified time before throwing NoSuchElementException on any element lookup" },
      { q: "What is JSON Schema validation in API testing?", options: ["Validating JSON file syntax only", "Verifying that an API response body conforms to a predefined structure, including field types, required fields, and constraints", "Creating JSON documentation", "Converting XML to JSON"], answer: "Verifying that an API response body conforms to a predefined structure, including field types, required fields, and constraints" },
      { q: "What is the purpose of a mock object in unit testing?", options: ["To mock (make fun of) bad code", "To simulate the behavior of real dependencies so tests remain isolated and predictable", "To create fake test data", "To mock user interactions"], answer: "To simulate the behavior of real dependencies so tests remain isolated and predictable" },
      { q: "What does 'flaky test' mean?", options: ["A test that always fails", "A test that produces inconsistent results — sometimes passing, sometimes failing — without code changes", "A test that tests UI animations", "A poorly written test"], answer: "A test that produces inconsistent results — sometimes passing, sometimes failing — without code changes" },
      { q: "What is Allure Framework used for in test automation?", options: ["Running Selenium tests", "Generating rich, interactive HTML reports from test execution results", "Managing test environments", "API performance testing"], answer: "Generating rich, interactive HTML reports from test execution results" },
      { q: "What is exploratory testing?", options: ["Testing without any documentation", "Simultaneous test design and execution where the tester actively explores the application without predefined scripts", "A type of automated testing", "Testing only new features"], answer: "Simultaneous test design and execution where the tester actively explores the application without predefined scripts" },
      { q: "Which HTTP method is typically used to update a partial resource?", options: ["PUT", "POST", "PATCH", "DELETE"], answer: "PATCH" },
      { q: "What is test coverage in software testing?", options: ["The number of test cases written", "A metric that measures the percentage of code or requirements exercised by a test suite", "The amount of time spent testing", "The number of bugs found"], answer: "A metric that measures the percentage of code or requirements exercised by a test suite" },
      { q: "What is the purpose of @DataProvider in TestNG?", options: ["To provide browser drivers", "To supply multiple sets of test data to a test method, enabling data-driven testing", "To define test groupings", "To configure parallel execution"], answer: "To supply multiple sets of test data to a test method, enabling data-driven testing" },
      { q: "What is load testing?", options: ["Testing on low-end hardware", "Testing system behavior and performance under expected and peak load conditions", "Testing file upload functionality", "Testing data loading in databases"], answer: "Testing system behavior and performance under expected and peak load conditions" },
    ],
  },
  {
    id: 'accenture-consulting',
    title: 'Accenture Technology Consultant Certification',
    duration: 30,
    questions: [
      { q: "What is the primary purpose of a Business Requirements Document (BRD)?", options: ["To describe technical implementation details", "To capture business objectives, needs, and the problems the project must solve, agreed upon by stakeholders", "To list project team members", "To define test cases"], answer: "To capture business objectives, needs, and the problems the project must solve, agreed upon by stakeholders" },
      { q: "In Agile, what is a 'sprint'?", options: ["A type of standup meeting", "A fixed time period (usually 1-4 weeks) during which a defined set of work must be completed", "A performance metric", "A retrospective meeting"], answer: "A fixed time period (usually 1-4 weeks) during which a defined set of work must be completed" },
      { q: "What does MECE stand for in consulting frameworks?", options: ["Most Effective Consulting Effort", "Mutually Exclusive, Collectively Exhaustive — a problem structuring principle", "Management, Execution, Communication, Evaluation", "Methodology, Engagement, Client, Execution"], answer: "Mutually Exclusive, Collectively Exhaustive — a problem structuring principle" },
      { q: "What is a user story in Agile?", options: ["A detailed technical specification", "A short, simple description of a feature from the end-user's perspective: 'As a [user], I want [goal] so that [benefit]'", "A bug report", "A sprint retrospective finding"], answer: "A short, simple description of a feature from the end-user's perspective: 'As a [user], I want [goal] so that [benefit]'" },
      { q: "What is a SWOT analysis?", options: ["A software development methodology", "An assessment of Strengths, Weaknesses, Opportunities, and Threats for a business or project", "A security vulnerability framework", "A financial modeling technique"], answer: "An assessment of Strengths, Weaknesses, Opportunities, and Threats for a business or project" },
      { q: "In Excel, what does VLOOKUP do?", options: ["Validates lookup values", "Looks up a value in the first column of a table and returns a value in the same row from a specified column", "Loops vertically through all cells", "Creates a vertical bar chart"], answer: "Looks up a value in the first column of a table and returns a value in the same row from a specified column" },
      { q: "What is the role of a Scrum Master?", options: ["To manage the project budget", "To facilitate Scrum ceremonies, remove impediments, and ensure the team follows Agile principles", "To write all user stories", "To make architectural decisions"], answer: "To facilitate Scrum ceremonies, remove impediments, and ensure the team follows Agile principles" },
      { q: "What is a stakeholder in project management?", options: ["Only the project sponsor", "Any individual, group, or organization that has an interest in or is affected by the project outcome", "Only internal team members", "Only the end customers"], answer: "Any individual, group, or organization that has an interest in or is affected by the project outcome" },
      { q: "What is the purpose of a SQL GROUP BY clause?", options: ["To sort results alphabetically", "To group rows with the same values in specified columns, enabling aggregate functions on each group", "To filter duplicate rows", "To join multiple tables"], answer: "To group rows with the same values in specified columns, enabling aggregate functions on each group" },
      { q: "What is change management in consulting?", options: ["Managing software version changes", "A structured approach to transitioning individuals and organizations from a current state to a desired future state", "Managing a project change request", "Version control for documents"], answer: "A structured approach to transitioning individuals and organizations from a current state to a desired future state" },
      { q: "What is Porter's Five Forces framework?", options: ["A project management methodology", "A model for analyzing an industry's competitive forces: rivalry, buyer power, supplier power, threat of new entrants, threat of substitutes", "A financial reporting standard", "A risk management framework"], answer: "A model for analyzing an industry's competitive forces: rivalry, buyer power, supplier power, threat of new entrants, threat of substitutes" },
      { q: "What does KPI stand for and why is it important?", options: ["Key Personnel Indicator — to track team performance", "Key Performance Indicator — a measurable value that shows how effectively objectives are being achieved", "Key Project Initiative — a planning tool", "Key Process Integration — a technical standard"], answer: "Key Performance Indicator — a measurable value that shows how effectively objectives are being achieved" },
      { q: "In project management, what is the Critical Path Method (CPM)?", options: ["A method for managing critical bugs", "A technique that identifies the longest sequence of dependent tasks determining the minimum project duration", "A client communication framework", "A risk scoring methodology"], answer: "A technique that identifies the longest sequence of dependent tasks determining the minimum project duration" },
      { q: "What is the definition of 'scope creep' in projects?", options: ["When a project finishes too early", "The uncontrolled expansion of project scope without corresponding adjustments to time, cost, and resources", "When requirements are too detailed", "When team members exceed their role boundaries"], answer: "The uncontrolled expansion of project scope without corresponding adjustments to time, cost, and resources" },
      { q: "What does a pivot table in Excel allow you to do?", options: ["Rotate the spreadsheet 90 degrees", "Summarize, analyze, and explore large datasets interactively by rearranging and grouping data", "Create pivot charts only", "Connect to external databases"], answer: "Summarize, analyze, and explore large datasets interactively by rearranging and grouping data" },
      { q: "What is a sprint retrospective in Scrum?", options: ["A meeting to review the product backlog", "A ceremony at the end of each sprint where the team inspects how they worked and identifies improvements", "A demo to stakeholders", "A planning session for the next sprint"], answer: "A ceremony at the end of each sprint where the team inspects how they worked and identifies improvements" },
      { q: "What is the purpose of a feasibility study?", options: ["To study project team feasibility", "To assess whether a proposed project is practical, achievable, and worth pursuing from technical, financial, and operational perspectives", "To document project requirements", "To create a project timeline"], answer: "To assess whether a proposed project is practical, achievable, and worth pursuing from technical, financial, and operational perspectives" },
      { q: "What is the difference between waterfall and Agile methodologies?", options: ["They are the same methodology", "Waterfall is sequential with fixed phases; Agile is iterative, allowing changes and delivering value incrementally", "Agile is for large projects; Waterfall for small ones", "Waterfall is faster than Agile"], answer: "Waterfall is sequential with fixed phases; Agile is iterative, allowing changes and delivering value incrementally" },
      { q: "In Excel, what does INDEX-MATCH do compared to VLOOKUP?", options: ["They are identical", "INDEX-MATCH is more flexible — it can look up values in any column (not just the first) and is faster on large datasets", "VLOOKUP is more powerful", "INDEX-MATCH only works horizontally"], answer: "INDEX-MATCH is more flexible — it can look up values in any column (not just the first) and is faster on large datasets" },
      { q: "What is a root cause analysis?", options: ["Analyzing the main project deliverable", "A systematic process for identifying the fundamental cause of a problem to prevent recurrence", "A financial analysis technique", "A stakeholder communication method"], answer: "A systematic process for identifying the fundamental cause of a problem to prevent recurrence" },
      { q: "What is the '80/20 rule' (Pareto Principle) in consulting?", options: ["80% of work should be done in 20% of time", "80% of outcomes typically come from 20% of causes — focus resources on the vital few", "A budget allocation guideline", "A testing coverage threshold"], answer: "80% of outcomes typically come from 20% of causes — focus resources on the vital few" },
      { q: "What does a product backlog contain in Scrum?", options: ["A list of completed tasks", "An ordered list of everything that might be needed in the product, maintained by the Product Owner", "Team member assignments", "Sprint velocity metrics"], answer: "An ordered list of everything that might be needed in the product, maintained by the Product Owner" },
      { q: "What is ROI and how is it calculated?", options: ["Return on Investment — (Net Profit / Cost of Investment) × 100", "Rate of Integration — a system metric", "Return on Input — (Output / Input) × 100", "Risk of Investment — a probability measure"], answer: "Return on Investment — (Net Profit / Cost of Investment) × 100" },
      { q: "What is the purpose of a gap analysis?", options: ["To analyze gaps in software code", "To identify the difference between the current state and the desired future state, guiding improvement actions", "To measure team performance gaps", "To analyze market gaps for new products only"], answer: "To identify the difference between the current state and the desired future state, guiding improvement actions" },
      { q: "What are acceptance criteria in Agile?", options: ["Criteria for accepting team members", "The conditions that a user story must satisfy to be considered complete and accepted by the Product Owner", "Performance benchmarks for the application", "The definition of done for the sprint"], answer: "The conditions that a user story must satisfy to be considered complete and accepted by the Product Owner" },
      { q: "What is a velocity in Scrum?", options: ["The speed of the development server", "The number of story points a team completes on average per sprint, used for future sprint planning", "The rate of bug resolution", "How fast code is deployed to production"], answer: "The number of story points a team completes on average per sprint, used for future sprint planning" },
      { q: "What is the primary goal of a daily standup (daily scrum)?", options: ["To report status to management", "To synchronize team activities, identify blockers, and plan the next 24 hours — typically 15 minutes", "To review completed work", "To plan the entire sprint"], answer: "To synchronize team activities, identify blockers, and plan the next 24 hours — typically 15 minutes" },
      { q: "What does 'data visualization' help achieve in consulting?", options: ["Only making reports look pretty", "Communicating complex data insights clearly to non-technical stakeholders through charts, graphs, and dashboards", "Replacing raw data in reports", "Automating data collection"], answer: "Communicating complex data insights clearly to non-technical stakeholders through charts, graphs, and dashboards" },
      { q: "What is a risk register in project management?", options: ["A list of team members' professional risks", "A document that identifies, analyzes, and records potential project risks along with mitigation strategies", "A financial risk report", "A compliance checklist"], answer: "A document that identifies, analyzes, and records potential project risks along with mitigation strategies" },
      { q: "What is the purpose of a stakeholder communication plan?", options: ["To list all stakeholder contact details", "To define how, when, and what information will be communicated to each stakeholder group throughout the project", "To manage stakeholder conflicts", "To document stakeholder approvals"], answer: "To define how, when, and what information will be communicated to each stakeholder group throughout the project" },
    ],
  },
];

let seeded = false;

export async function ensureData() {
  if (typeof window === 'undefined') return;
  if (seeded) return;
  if (storage.isSeeded()) { seeded = true; return; }
  await storage.seedRoadmaps(roadmaps);
  const quizData = quizzes.map(q => ({
    id: q.id,
    title: q.title,
    duration: q.duration,
    questions: q.questions.map((item, i) => ({ id: i, question: item.q, options: item.options, answer: item.answer })),
  }));
  await storage.seedQuizzes(quizData);
  seeded = true;
}
